### ISSUE TITLE
A prospective user wants to register for a specific existing group to use the application and has been invited to a group by a group owner

### ISSUE THREAD

**Issue by goosinator868** [goosinator868/propbox#11]
Given: | The prospective user is connected to the internet
The prospective user is on the user registration page
-- | --
When: | The prospective user enters their email address
The prospective user enters their desired password
The prospective user enters the inviting group owner’s group name
The prospective user presses the “register” button
Then: | The prospective user is registered in the entered group and becomes a standard user.

See readme for done criteria.

**Comment by hvpeteet** [comment]
With the decision to not implement groups this will no longer be implemented.
