### ISSUE TITLE
Some permissions are not enforced.

### ISSUE THREAD

**Issue by hvpeteet** [goosinator868/propbox#113]
There may be more issues, in which case you should add them to the thread by adding a comment. Currently, I have noticed this bug in regards to:

1. ~~A Standard User can Add Item (Should not be able to)~~
2. ~~Private lists can be viewed by copying URLs~~
3. A Standard User can try to add items to public lists (does not work, but does not report failure)

I am sure there are more so please add them to this thread.

**Comment by wille179** [comment]
You're going to have to modify navbar.html, possibly making it into a JINJA template. The navbar has an add-item button.

**Comment by wille179** [comment]
Standard users can now no longer add an item. The button in the navbar still exists, but it merely redirects to home for standard users.

**Comment by wille179** [comment]
Users can now no longer access private lists by copying links.
