### ISSUE TITLE
A prospective user wants to register a new group to use the application

### ISSUE THREAD

**Issue by goosinator868** [goosinator868/propbox#12]
Given: | The prospective user is connected to the internet
The prospective user is on the group owner registration page
-- | --
When: | The prospective user enters their email address
The prospective user enters their desired password
The prospective user enters the new group name and the group name does not already exist
The prospective user presses the “register” button
Then: | A new group is created and the prospective user is registered in the entered group as a group owner.

See readme for done criteria.

**Comment by hvpeteet** [comment]
With the decision to not implement groups this will no longer be implemented.
