### ISSUE TITLE
A trusted user wants to restore a costume that was accidentally removed

### ISSUE THREAD

**Issue by goosinator868** [goosinator868/propbox#26]
Given: | The user is on the trash management page
The user is logged in
The costume is in the trash
-- | --
When: | The user selects an item for restoration and submits
Then: | The user is shown a message notifying them the costume has been removed to the trash and added back to the inventory
The costume is removed from the trash inventory and placed back into the normal inventory
The user returns to the trash management page

See readme for done criteria.

**Comment by wille179** [comment]
Pending review from Henry.
