### ISSUE TITLE
User Interface Polish

### ISSUE THREAD

**Issue by goosinator868** [goosinator868/propbox#87]
Mobile development pages are underdeveloped.

Done when all associated stories are finished.

**Comment by wille179** [comment]
From my personal TODO list:

- Fix popups for desktop and mobile
--Text centering/view formatting
- Adapt changes for mobile view.
- Expand Review edits/Deletions with more item details.
- Fix Review Edits popup (need more information)
- Review Deletions description text (more details, which pane does what?).
- Trusted User/Admin notification on home page (Better formatting options?)

(Sorry it's vague.)
